apiVersion: v1
kind: Pod
metadata:
  annotations:
    paloaltonetworks.com/firewall: pan-fw
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always